const Map<String, String> stArabic = {
  'appName': 'مفهوم',
  'lblSelect': 'اختر',
  'onBoardingFirstMsg': 'ادرس حسب وتيرتك الخاصة مع مقاطع فيديو\nتفاعلية، اختبارات، ومحتوى مخصص.',
  'onBoardingFirstTitle': 'المعرفة هي\nقوتك الخارقة',
  'onBoardingSecondMsg': 'ابقَ متحفزًا مع تتبع التقدم\nفي الوقت الحقيقي ورؤى الإنجاز.',
  'onBoardingSecondTitle': 'نمُ كل يوم\nوتعلم شيئًا جديدًا',
  'onBoardingThirdMsg': 'استكشف مجموعة واسعة من المواد التعليمية\nالمصممة لمساعدتك على النمو والنجاح.',
  'onBoardingThirdTitle': 'تعلّم أي شيء\nمن أي مكان',
  'lblSkip': 'تخطي',
  'lblNext': 'التالي',
  'lblGetStarted': 'ابدأ الآن',
  'lblDaysRemaining': 'متبقي @value يوم',

  // Select Language Screen
  'selectLanguage': 'اختر اللغة',
  'selectLanguageInfo': 'يرجى اختيار لغتك المفضلة للمتابعة',
  'lblEnglish': 'English',
  'lblArabic': 'عربي',
  'lblSelectLanguage': 'يرجى اختيار لغة',

  // Login Screen
  'loginTitle': 'تسجيل الدخول',
  'loginSubtitle': 'سيتم إرسال كلمة مرور لمرة واحدة\nإلى رقم الجوال المُدخل',
  'lblMobileNumber': 'رقم الجوال',
  'lblEnterMobileNumber': 'أدخل رقم الجوال',
  'lblIAgree': 'أوافق وأقبل ',
  'lblTermsOfService': 'شروط الخدمة',
  'lblAnd': ' و ',
  'lblPrivacyPolicy': 'سياسة الخصوصية',
  'lblGetOTP': 'احصل على كلمة المرور لمرة واحدة',
  'lblContinueAsGuest': 'الدخول كضيف',
  'loginRequired': "تسجيل الدخول مطلوب",
  'loginToAccessPackages': "يرجى تسجيل الدخول للوصول",
  'pleaseLoginToAccessAccount': 'الرجاء تسجيل الدخول للوصول إلى الحساب',

  // OTP Verification Screen
  'otpVerificationTitle': 'التحقق من كلمة المرور لمرة واحدة',
  'otpVerificationSubtitle': 'أدخل رمز التحقق المكون من 6 أرقام\nالمرسل إلى هاتفك',
  'lblVerify': 'تحقق',
  'lblResendCode': 'إعادة إرسال الرمز',
  'lblResendCodeIn': 'إعادة إرسال الرمز خلال ',

  // Profile Setup Screen
  'profileSetupTitle': 'إعداد الملف الشخصي',
  'lblEditProfile': 'تعديل الملف الشخصي',
  'lblFullName': 'الاسم الكامل',
  'lblEmail': 'البريد الإلكتروني',
  'lblSelectGrade': 'اختر الصف',
  'lblStream': 'المسار',
  'lblScience': 'علمي',
  'lblCommerce': 'تجاري',
  'lblSave': 'حفظ',
  'lblSelectProfileImage': 'اختر صورة الملف الشخصي',
  'lblCamera': 'الكاميرا',
  'lblGallery': 'المعرض',

  // Home Screen
  'guest': 'زائر',
  "welcomeBack": "مرحبًا بعودتك،",
  'lblDummyUser': "أحمد الخاتم",
  'lblDummyLocation': "الكويت",
  "searchEvents": "البحث عن الأحداث...",
  "continueLearning": "واصل التعلم",
  "viewAll": "عرض الكل",
  "grade": "الصف @grade",
  "selectGrade": "اختر الصف",
  "todaysSchedule": "جدول اليوم",
  "examPackage": "حزمة الامتحان",
  "coursePackage": "حزمة الدورة",
  "buyPackage": "شراء الحزمة",
  "lblSelectedGrade": "الصف المحدد",
  "lblSelectedStream": "المسار المحدد",
  'lblPaymentFailed': 'فشل الدفع. لم يتم إكمال معاملتك.',
  'lblPaymentSuccessful': 'تم الدفع بنجاح. تم إكمال معاملتك بأمان.',
  'lblPdfDownloadedSuccess': 'تم تنزيل ملف بي دي إف بنجاح',
  'lblPermissionStorage': 'تم رفض الإذن، يلزم الوصول إلى التخزين لتنزيل المستند',
  'timeUpNextQuestion': "انتهى الوقت! يتم الانتقال إلى السؤال التالي",

  // Grade Options
  'grade6': 'الصف السادس',
  'grade7': 'الصف السابع',
  'grade8': 'الصف الثامن',
  'grade9': 'الصف التاسع',
  'grade10': 'الصف العاشر',
  'grade11': 'الصف الحادي عشر',
  'grade12': 'الصف الثاني عشر',

  // Dashboard Screen
  'lblHome': 'الرئيسية',
  'lblPackages': 'الحزم',
  'lblMyPackages': 'حزمتي',
  'lblGoals': 'الأهداف',
  'lblSetting': 'الإعدادات',

  // Course Module
  'lblMathematics': 'الرياضيات',
  'lblLearnMathematics': 'تعلم الرياضيات',
  'lblChapterInfo':
      'لوريم إيبسوم دولور سيت أميت كونسيكتيتور. أميت أورسي أليكويت ساسبنديسي سيم إست إيجيت بوروس كونغي إيتيام. أوت نيكيه فينيناتيس آك إياكيوليس تريستيك نيزي فيتاي كونفاليس.',
  'lblReadmore': 'اقرأ المزيد',
  "lblSemester": "الفصل الدراسي",
  'lblSemester1': 'الفصل الدراسي 1',
  'lblSemester2': 'الفصل الدراسي 2',
  'lblMath102FreeTrial': 'تجربة مجانية لمادة الرياضيات 102',
  'lblFreeAccess': 'وصول مجاني',
  'lblFundamentalMathematics': 'الرياضيات الأساسية',
  'lblChapterOne': 'الفصل الأول',
  'lblChapterTwo': 'الفصل الثاني',
  'lblChapterThree': 'الفصل الثالث',
  'lblChapterFour': 'الفصل الرابع',
  'lblChapterFive': 'الفصل الخامس',
  'lblBuyFullPackageAt': 'اشترِ الحزمة الكاملة بسعر @value دينار كويتي',
  'lblInstructorTitle': 'المُعلِّم: @name',
  'lblInstructorName': 'فلويد مايلز',
  'lblAboutThe': 'حول @name',
  'lblEvenAndOddFunc': 'الدوال الزوجية والفردية',
  'lblMin': '@value دقيقة',
  'lblBuySubject': 'اشترِ المادة بسعر @value دينار كويتي',
  'lblReviews': '(@value مراجعة)',
  'lblReadMore': 'اقرأ المزيد',
  "lblPleasePurchasePackageFirst": "يجب عليك شراء حزمة للوصول إلى هذه الميزة.",

  'lblHours': '@value ساعة',
  'lblCourseDetails': 'تفاصيل الدورة',
  'lblOverallProgress': 'التقدم العام',
  'lblChapter': '@currentChapter/@totalChapter فصل',
  'lblDownloadPdf': 'تحميل ملف بي دي إف',
  'lblMcqExam': 'اختبار الاختيار من متعدد',

  // Payment Success
  'lblPaymentSuccess': 'تم الدفع بنجاح',
  'lblPaymentSuccessInfo': 'تم الدفع بنجاح وتمت معالجة معاملتك بأمان.',
  'lblAmount': 'المبلغ',
  'lblGoToMyCourse': 'اذهب إلى دورتي',
  'lblKwd': '@value دينار كويتي',
  'lblStartExam': 'ابدأ الاختبار',
  "lblExamHistory": "سجل الامتحان",
  'lblExitExamConfirmation': 'هل أنت متأكد أنك تريد إنهاء الامتحان؟',
  'lblYes': 'نعم',
  'lblNo': 'لا',
  'lblWellDone': 'أحسنت!',
  'lblIncorrect': 'عذراً، إجابة خاطئة',
  'lblUnanswered': 'غير مجاب',
  'lblQuestion': 'سؤال',

  // Exam Complete Screen
  "lblExamCompleteCongrats": "تهانينا لقد\nأكملت هذا الاختبار",
  "lblExamCompleteGreatJob": "عمل رائع، @username\nأديت جيدًا",
  "lblExamCompleteYourScore": "درجتك",
  "lblExamCompleteViewResult": "عرض النتيجة",

  // Validation Strings
  'lblAgreeTermsAndConditions': 'يرجى الموافقة على الشروط والأحكام',
  'lblEmptyMobileNumberOrEmail': 'يرجى إدخال رقم الهاتف أو البريد الإلكتروني',
  'lblEmptyEmail': 'يرجى إدخال البريد الإلكتروني',
  'lblEnterEmail': 'أدخل البريد الإلكتروني',
  'lblValidEmail': 'يرجى إدخال بريد إلكتروني صالح',
  'lblEmptyMobile': 'يرجى إدخال رقم الهاتف',
  'lblEmptyAlternateMobile': 'يرجى إدخال رقم هاتف بديل',
  'lblValidMobileNumber': 'يرجى إدخال رقم هاتف صالح',
  'lblValidAlternateMobileNumber': 'يرجى إدخال رقم هاتف بديل صالح',
  'lblEmptyPassword': 'يرجى إدخال كلمة المرور',
  'lblValidPassword': 'يرجى إدخال كلمة مرور صالحة',
  'lblEnterFullName': 'أدخل الاسم الكامل',
  'lblEmptyFullName': 'يرجى إدخال الاسم الكامل',
  'lblEmptyConPassword': 'يرجى إدخال تأكيد كلمة المرور',
  'lblPasswordAndConPasswordNotMatch': 'كلمة المرور وتأكيدها غير متطابقين',
  'lblPleaseAcceptTermsAndConditions': 'يرجى قبول الشروط والأحكام',
  'lblPleaseEnterOTP': 'يرجى إدخال رمز التحقق',
  'lblPleaseEnterValidOTP': 'يرجى إدخال رمز تحقق صالح',
  'lblPleaseSelectDOB': 'يرجى اختيار تاريخ الميلاد',
  'lblPleaseSelectGender': 'يرجى اختيار الجنس',
  'lblPleaseSelectProfilePhoto': 'يرجى اختيار صورة الملف الشخصي',
  'lblEmptyExistingPassword': 'يرجى إدخال كلمة المرور الحالية',
  'lblEmptyNewPassword': 'يرجى إدخال كلمة مرور جديدة',
  'lblEmptyPassportPhoto': 'يرجى اختيار صورة الجواز',
  'lblEmptyDate': 'يرجى اختيار التاريخ',
  'lblEmptyNationalIdPassportNo': 'يرجى إدخال رقم الهوية/جواز السفر',
  'lblValidNationalIdPassportNo': 'يرجى إدخال رقم هوية/جواز سفر صالح',
  'lblEmptyPostalAddress': 'يرجى إدخال العنوان البريدي',
  'lblEmptyCity': 'يرجى إدخال المدينة',
  'lblPleaseSelectGrade': 'يرجى اختيار الصف',
  'lblPleaseSelectStream': 'يرجى اختيار المسار',
  'lblSearchHint': 'اكتب للبحث',
  'lblPleaseSelectAnswer': 'يرجى اختيار إجابة قبل المتابعة',
  'lblNoInternet': 'لا يوجد اتصال بالإنترنت',
  'lblNoData': 'لم يتم العثور على بيانات',
  'lblRetry': 'أعد المحاولة',
  'lblDataNotAvailable': 'البيانات غير متوفرة',
  'lblDataNotAvailableInfo': 'البيانات المطلوبة غير موجودة أو\nغير متاحة حالياً.',

  // Continue your learning
  'lblLessons': 'دروس',
  'lblLesson': 'درس',
  'lblModules': 'وحدات',
  'lblModule': 'وحدة',

  // Course Titles
  'courseArabicLanguageTitle': 'دورة اللغة العربية',
  'courseDuration': '08:30 دقيقة',

  // Exam Package Titles
  'examScienceTitle': 'حزمة امتحان العلوم',
  'examMathematicsTitle': 'حزمة امتحان الرياضيات',
  'examLifeSkillsTitle': 'حزمة امتحان المهارات الحياتية',
  'examSocialStudiesTitle': 'حزمة الدراسات الاجتماعية',
  'examArabicTitle': 'اللغة العربية',
  'examComputerTitle': 'حزمة امتحان الحاسوب',
  'examDuration': '08:30 ساعة',
  'examLanguage': 'الإنجليزية، العربية',
  'examType': 'أسئلة اختيار من متعدد',
  'examRating': 'التقييم',
  'examPrice': 'السعر',
  "mathQuestion1": "ما هو حاصل ضرب ٧ × ٨؟",
  "mathQuestion1Option1": "٥٤",
  "mathQuestion1Option2": "٥٦",
  "mathQuestion1Option3": "٦٤",
  "mathQuestion1Option4": "٥٨",

  "mathQuestion2": "ما هو الجذر التربيعي لـ ١٤٤؟",
  "mathQuestion2Option1": "١٠",
  "mathQuestion2Option2": "١١",
  "mathQuestion2Option3": "١٢",
  "mathQuestion2Option4": "١٣",
  "mathQuestion3": "ما هو 15٪ من 200؟",
  "mathQuestion3Option1": "20",
  "mathQuestion3Option2": "25",
  "mathQuestion3Option3": "30",
  "mathQuestion3Option4": "35",

  "mathQuestion4": "أي من الأرقام التالية هو عدد أولي؟",
  "mathQuestion4Option1": "12",
  "mathQuestion4Option2": "15",
  "mathQuestion4Option3": "17",
  "mathQuestion4Option4": "21",

  "mathQuestion5": "ما قيمة 9 تربيع؟",
  "mathQuestion5Option1": "18",
  "mathQuestion5Option2": "27",
  "mathQuestion5Option3": "72",
  "mathQuestion5Option4": "81",
  'lblSubmit': 'إرسال',
  'lblFinish': 'إنهاء',

  // Course Package Titles
  'courseMathematicsTitle': 'الرياضيات',
  'courseScienceTitle': 'العلوم',
  'courseArabicTitle': 'اللغة العربية',
  'courseSocialStudiesTitle': 'الدراسات الاجتماعية',
  'courseComputerTitle': 'الحاسوب',
  'courseLifeSkillsTitle': 'مهارات الحياة',
  'lblEnrollMe': 'سجّلني بـ @value د.ك / سنويًا',
  'lblEnrollSemester': 'اشترك في @semester بسعر @valueKWD / سنويًا',
  'lblEnrollBothSemester': 'سجّل الفصلين بـ @value د.ك / سنويًا',
  'lblEnrollExamPackage': 'اشترك في باقة الامتحان بسعر @value دينار كويتي / سنويًا',

  // Learning Course Titles
  'learningCourseArabicTitle': 'دورة اللغة العربية',
  'learningCourseDuration': '٠٨:٣٠ دقيقة',

  'scheduleLiveExamReviewTitle': 'مراجعة الامتحان المباشر',
  'scheduleLiveExamReviewSubtitle': 'الأستاذ زاهر شلهوب',

  'scheduleRenewableEnergyLessonTitle': 'درس الطاقة المتجددة',
  'scheduleRenewableEnergyLessonSubtitle': 'خطة الدراسة',

  // Setting Screen
  'lblSettingsPreferences': 'الإعدادات والتفضيلات',
  'lblMore': 'المزيد',
  'lblAccount': 'الحساب',
  'lblLanguage': 'اللغة',
  'lblMySaveList': 'قائمتي المحفوظة',
  'lblStatistics': 'الإحصائيات',
  'lblMyPurchases': 'مشترياتي',
  'lblMyDownloads': 'تنزيلاتي',
  'lblAboutUs': 'معلومات عنا',
  'lblFAQ': 'الأسئلة المتكررة',
  'lblTermsConditions': 'الشروط والأحكام',
  'lblContactUs': 'اتصل بنا',
  'lblDeleteAccount': 'حذف الحساب',
  'lblLogout': 'تسجيل الخروج',
  'lblAreYouSure': 'هل أنت متأكد؟',
  'lblDeleteAccountInfo': 'إذا كنت متأكدًا من أنك تريد حذف\nحسابك نهائيًا، يرجى الضغط على حذف\nالحساب أدناه',
  'lblCancel': 'إلغاء',
  'lblOkay': 'حسنًا',
  'lblYesDelete': 'نعم، احذف',
  'lblAreYouSureLogout': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'lblLogoutInfo': 'يمكنك تسجيل الخروج من حسابك في أي وقت. لا تقلق - سيتم حفظ بياناتك، ويمكنك تسجيل الدخول مرة أخرى\nمتى كنت مستعدًا.',
  'lblGoBack': 'العودة',
  "lblVersion": "الإصدار ",

  // My Downloads Screen
  'lblCourseVideo': 'فيديو الدورة',
  'lblCoursePdf': 'ملف PDF للدورة',

  // Notifications Screen
  "notifications": "الإشعارات",
  "clearAll": "مسح الكل",
  "upcomingExamAlert": "تنبيه بالامتحان القادم",
  "chapterDeadlineReminder": "تذكير بموعد انتهاء الفصل",
  "chapterProgressReminder": "تذكير بتقدم الفصل",
  "pendingChapterCompletionReminder": "تذكير بإكمال الفصل المعلق",
  "missedChapterReminder": "تذكير بالفصل الفائت",
  "maintainStreakReminder": "تذكير بالحفاظ على السلسلة",
  "lostStreakAlert": "تنبيه بفقدان السلسلة",
  "shipmentNotification": "إشعارات الشحن (الامتحانات الفصلية)",
  "defaultMessage": "مرحبًا! كيف يمكنني مساعدتك؟",

  // My Save List Screen
  "mySaveList": "قائمة الحفظ",
  "saveCourse": "حفظ الدورة",
  "savedChapter": "الفصول المحفوظة",
  "savedExam": "الاختبار المحفوظ",

  // Course Content
  "packageA": "الحزمة أ",
  "mathematicsDescription": "الرياضيات هي لغة الأنماط والمنطق، تُستخدم لفهم ووصف العالم من حولنا...",
  "mathematics": "الرياضيات",
  "factoringPolynomials": "تحليل كثيرات الحدود",
  "durationMinutes": "01:30 دقيقة",

  // contact us screen
  "weLoveToHearFromYou": "يسعدنا الاستماع إليك!",
  "contactUsDescription":
      "سواء كانت لديك اقتراحات لتحسين الخدمة، أو موضوع ترغب في مناقشته، أو مشكلة تحتاج إلى حل — لا تتردد في التواصل معنا.",
  "callUs": "اتصل بنا",
  "phoneNumber": "(+965) 22761129",
  "emailUs": "أرسل لنا بريدًا",
  "email": "البريد الإلكتروني",
  "connectSocialMedia": "تواصل معنا عبر وسائل التواصل الاجتماعي",
  "instagram": "انستغرام",
  "instagramFollowers": "0 ألف متابع",
  "instagramPosts": "0 منشور",
  "telegram": "تيليجرام",
  "telegramFollowers": "0 ألف متابع",
  "telegramPosts": "0 منشور",
  "facebook": "فيسبوك",
  "facebookFollowers": "0 ألف متابع",
  "facebookPosts": "0 منشور",
  "whatsapp": "واتساب",
  "whatsappAvailability": "متاح من الاثنين إلى الجمعة • 9 صباحًا – 5 مساءً",
  "myCourse": "دورتي",
  "noSavedCoursesYet": "لا توجد دورات محفوظة بعد",
  "lblClearAll": "مسح الكل",
  "lblPaymentSummary": "ملخص الدفع",
  "lblPromoCode": "رمز ترويجي",
  "lblApplyPromoCode": "تطبيق الرمز الترويجي",
  "lblAllPromoCode": "جميع الرموز الترويجية",
  "lblApplyPromocode": "تطبيق الرمز الترويجي",
  "lblEnterPromoCode": "أدخل الرمز الترويجي",
  "lblApply": "تطبيق",
  "lblRemove": "إزالة",
  "lblOrderSummary": "ملخص الطلب",
  "lblSubTotal": "المجموع الفرعي",
  "lblDiscount": "الخصم",
  "lblTotal": "الإجمالي",
  'lblExpires': 'تنتهي في',
  'lblPaymentFailure': 'فشل الدفع',
  'lblPaymentFailureInfo': 'فشل الدفع، لم تكتمل معاملتك.',
  'lblPayNow': 'ادفع الآن',
  'lblWriteReviewTitle': 'اكتب تقييمًا',
  'lblRatingInfo': 'كيف تقيم جودة هذا المنتج؟',
  'lblWriteYourReview': 'اكتب تقييمك',
  'lblReviewHint': 'اكتب تقييمك هنا...',
  'lblCharacterRemaining': 'تبقى @value حرفًا',
  'lblSubmitReview': 'إرسال التقييم',
  'lblExamAttempted': 'تمت محاولة الامتحان',
  'lblNoPromoCode': 'لم يتم العثور على رمز ترويجي.',
  'lblReview': 'التقييم',
  'lblWriteReview': 'اكتب تقييمًا',
  'lblPleaseAddReview': 'يرجى تقديم التقييم',
  'lblNoReviews': 'لا توجد تقييمات بعد.',
  "lblStarSingular": "@value نجمة",
  "lblStarPlural": "@value نجمات",
  'lblGoToDashboard': 'الذهاب إلى الصفحة الرئيسية',
  'lblWatched': 'تمت المشاهدة',
  'lblDownloadingPdf': 'جارٍ تنزيل ملف بي دي إف',
  'lblOpenPdf': 'فتح ملف بي دي إف',
  'lblGoToDownloads': "اذهب إلى التنزيلات",
  'lbTypeHere': 'اكتب هنا...',
  'lblNoInternetInfo': 'يرجى التحقق من الاتصال وحاول مرة أخرى',
  'lblPleaseLoginToAccessLink': 'يرجى تسجيل الدخول للوصول إلى هذا الرابط.',
  'lblCheckOutThis': 'تحقق من هذا على مفهوم: @value',
  "lblOrderDetails": "تفاصيل الطلب",
  "lblPurchasedOn": "تم الشراء في",
  "lblExpiresOn": "تاريخ الانتهاء",
  "lblOrderId": "رقم الطلب",
  "lblPlanType": "نوع الخطة",
  "lblPackageIsActive": "الباقة مفعّلة",
  "lblPackageExpired": "انتهت صلاحية الباقة",
  "lblRemainingDays": "الأيام المتبقية",
  "lblOrderAmount": "قيمة الطلب",
  'lblLinkError': 'تعذر فتح الرابط',
  'lblEmailError': 'تعذر فتح تطبيق البريد الإلكتروني',
  'lblCallError': 'تعذر بدء المكالمة',

  'lblCheckYourConnection': 'يرجى التحقق من اتصال الإنترنت.',
  'lblSomethingWentWrong': 'حدث خطأ ما.',
  'lblAutoLogout': 'تم تسجيل الخروج تلقائيًا بسبب انتهاء الجلسة.',
  'lblSessionExpired': 'انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى.',
  'lbl100Message': 'عمل رائع، @username،',
  'lbl100SubMessage': 'أحسنت.',
  'lbl99Message': 'جهد جيد!\nواصل التدريب، @username',
  'lbl99SubMessage': 'أنت تتحسن!',
  'lbl50Message': 'لا تقلق!\nلا بأس، @username.',
  'lbl50SubMessage': 'هذه مجرد بداية. راجع المادة وحاول مرة أخرى!',
  'lblExpired': 'منتهي الصلاحية',

  'lblExamWarningMessage': "مغادرة التطبيق أو وضعه في الخلفية أثناء الامتحان سيؤدي إلى الإنهاء التلقائي للمحاولة، وستُعتبر محاولتك مكتملة.",
  'lblReadLess': 'اقرأ أقل',
};
