const Map<String, String> stEnglish = {
  'appName': 'Mafhoom',
  'lblSelect': 'Select',
  'onBoardingFirstMsg': 'Study at your own pace with interactive\nvideos, quizzes, and personalized content.',
  'onBoardingFirstTitle': 'Knowledge is Your\nSuperpower',
  'onBoardingSecondMsg': 'Stay motivated with real-time progress\ntracking and achievement insights.',
  'onBoardingSecondTitle': 'Grow Every Day\nLearn Something New',
  'onBoardingThirdMsg': 'Explore a wide range of subjects designed\nto help you grow and succeed.',
  'onBoardingThirdTitle': 'You Learn anything\nAnywhere ',
  'lblSkip': 'Skip',
  'lblNext': 'Next',
  'lblGetStarted': 'Get Started',

  // Select Language Screen
  'selectLanguage': 'Select Language',
  'selectLanguageInfo': 'Kindly select your preferred language to proceed',
  'lblEnglish': 'English',
  'lblArabic': 'عربي',
  'lblSelectLanguage': 'Please select a language',

  // Login Screen
  'loginTitle': 'Login',
  'loginSubtitle': 'A One-Time Password (OTP) will\nbe sent to the provided Mobile Number',
  'lblMobileNumber': 'Mobile Number',
  'lblPassword': 'Password',
  'lblConfirmPassword': 'Confirm Password',
  'lblEnterPassword': 'Enter Password',
  'lblEnterMobileNumber': 'Enter Mobile Number',
  'lblIAgree': 'I agree and accept the ',
  'lblTermsOfService': 'Terms of Service',
  'lblAnd': ' and ',
  'lblPrivacyPolicy': 'Privacy Policy',
  'lblGetOTP': 'Get OTP',
  'lblContinueAsGuest': 'Continue as Guest',
  'lblSignUp': 'Sign Up',
  'loginRequired': "Login Required",
  'loginToAccessPackages': "Please login to Access",
  'pleaseLoginToAccessAccount': 'Please Login to Access Account',

  // OTP Verification Screen
  'otpVerificationTitle': 'OTP Verification',
  'otpVerificationSubtitle': 'Enter 6 digit verification code sent to\nyour phone',
  'lblVerify': 'Verify',
  'lblResendCode': 'Resend Code',
  'lblResendCodeIn': 'Resend Code in ',

  // Profile Setup Screen
  'profileSetupTitle': 'Profile Setup',
  'lblEditProfile': 'Edit Profile',
  'lblFullName': 'Full Name',
  'lblEmail': 'Email',
  'lblSelectGrade': 'Select Grade',
  'lblStream': 'Stream',
  'lblScience': 'Science',
  'lblCommerce': 'Commerce',
  'lblSave': 'Save',
  'lblSelectProfileImage': 'Select Profile Image',
  'lblCamera': 'Camera',
  'lblGallery': 'Gallery',

  // Home Screen
  'guest': 'Guest',
  "welcomeBack": "Welcome back",
  'lblDummyUser': "Ahmed Al-Khatam",
  'lblDummyLocation': "kuwait",
  "searchEvents": "Search Events...",
  "continueLearning": "Continue your learning",
  "viewAll": "View all",
  "grade": "Grade @grade",
  "selectGrade": "Select Grade",
  "todaysSchedule": "Today's Schedule",
  "examPackage": "Exam Package",
  "coursePackage": "Course Package",
  "buyPackage": "Buy Package",
  "lblSelectedGrade": 'Selected Grade',
  "lblSelectedStream": 'Selected Stream',
  'lblPaymentFailed': 'Payment failed. Your transaction could not be completed.',
  'lblPaymentSuccessful': 'Payment successful. Your transaction has been completed securely.',
  'lblPdfDownloadedSuccess': 'PDF downloaded successfully',
  'lblPermissionStorage': 'Permission Denied, Storage access is required to download PDF',
  'timeUpNextQuestion': "Time's up! Moving to next question",

  // Grade Options
  'grade6': 'Grade 6',
  'grade7': 'Grade 7',
  'grade8': 'Grade 8',
  'grade9': 'Grade 9',
  'grade10': 'Grade 10',
  'grade11': 'Grade 11',
  'grade12': 'Grade 12',

  // Dashboard Screen
  'lblHome': 'Home',
  'lblPackages': 'Packages',
  'lblMyPackages': 'My Packages',
  'lblGoals': 'Goals',
  'lblSetting': 'Setting',

  // Course Module
  'lblMathematics': 'Mathematics',
  'lblLearnMathematics': 'Learn Mathematics',
  'lblChapterInfo':
      'Lorem ipsum dolor sit amet consectetur. Amet orci aliquet suspendisse sem est eget purus congue etiam. Ut neque venenatis ac iaculis tristique nisi vitae convallis.',
  'lblReadmore': 'Readmore',
  'lblSemester': 'Semester',
  'lblSemester1': 'Semester 1',
  'lblSemester2': 'Semester 2',
  'lblMath102FreeTrial': 'Math 102 Free Trial',
  'lblFreeAccess': 'Free Access',
  'lblFundamentalMathematics': 'Fundamental Mathematics',
  'lblChapterOne': 'Chapter One',
  'lblChapterTwo': 'Chapter Two',
  'lblChapterThree': 'Chapter Three',
  'lblChapterFour': 'Chapter Four',
  'lblChapterFive': 'Chapter Five',
  'lblBuyFullPackageAt': 'Buy full package at @value KWD',
  'lblInstructorTitle': 'Intructor: @name',
  'lblInstructorName': 'Floyd Miles',
  'lblAboutThe': 'About the @name',
  'lblEvenAndOddFunc': 'Even and Odd Functions',
  'lblMin': '@value Min',
  'lblBuySubject': 'Buy Subject @value KWD',
  'lblReviews': '(@value Reviews)',
  'lblReadMore': 'Read more',
  "lblPleasePurchasePackageFirst": "You need to purchase a package to access this feature.",

  'lblHours': '@value Hrs',
  'lblCourseDetails': 'Course Details',
  'lblOverallProgress': 'Overall Progress',
  'lblChapter': '@currentChapter/@totalChapter Chapter',
  'lblDownloadPdf': 'Download PDF',
  'lblMcqExam': 'MCQs Exam',

  // Payment Success
  'lblPaymentSuccess': 'Payment Successful',
  'lblPaymentSuccessInfo': 'Payment Successful your transaction\nhas been completed securely.',
  'lblAmount': 'Amount',
  'lblGoToMyCourse': 'Go to my course',
  'lblKwd': '@value KWD',
  'lblStartExam': 'Start Exam',
  'lblDaysRemaining': '@value days remaining',

  // Exam Complete Screen
  "lblExamCompleteCongrats": "Congratulations you\ncompleted this MCQs",
  "lblExamCompleteGreatJob": "Great job, @username\nyou done well",
  "lblExamCompleteYourScore": "Your Score",
  "lblExamCompleteViewResult": "View Result",
  "lblExamHistory": "Exam History",
  'lblExitExamConfirmation': 'Are you sure you want to quit the exam?',
  'lblYes': 'Yes',
  'lblNo': 'No',
  'lblWellDone': 'Well done!',
  'lblIncorrect': 'Oops, incorrect',
  'lblUnanswered': 'Unanswered',
  'lblQuestion': 'Question',

  // Validation Strings
  'lblAgreeTermsAndConditions': 'Please agree to terms and conditions',
  'lblEmptyMobileNumberOrEmail': 'Please enter mobile number or email!',
  'lblEmptyEmail': 'Please enter email',
  'lblEnterEmail': 'Enter Email',
  'lblValidEmail': 'Please enter valid email',
  'lblEmptyMobile': 'Please enter mobile number',
  'lblEmptyAlternateMobile': 'Please enter alternate mobile number',
  'lblValidMobileNumber': 'Please enter valid mobile number',
  'lblValidAlternateMobileNumber': 'Please enter valid alternate mobile number',
  'lblEmptyPassword': 'Please enter password',
  'lblValidPassword': 'Please enter valid password',
  'lblEnterFullName': 'Enter Full Name',
  'lblEmptyFullName': 'Please enter full name',
  'lblEmptyConPassword': 'Please enter confirm password',
  'lblPasswordAndConPasswordNotMatch': 'Password and confirm password does not match',
  'lblPleaseAcceptTermsAndConditions': 'Please accept terms & conditions',
  'lblPleaseEnterOTP': 'Please enter OTP',
  'lblPleaseEnterValidOTP': 'Please enter valid OTP',
  'lblPleaseSelectGrade': 'Please select grade',
  'lblPleaseSelectStream': 'Please select stream',
  'lblSearchHint': 'Type to search',
  'lblPleaseSelectAnswer': 'Please select an answer before continuing',
  'lblNoInternet': 'No Internet Connection',
  'lblNoData': 'No data found',
  'lblRetry': 'Retry',
  'lblDataNotAvailable': 'Data Unavailable',
  'lblDataNotAvailableInfo': 'The required data is currently not\npresent or accessible.',

  // Continue your learning
  'lblLessons': 'Lessons',
  'lblLesson': 'Lesson',
  'lblModules': 'Modules',
  'lblModule': 'Module',

  // Course Titles
  'courseArabicLanguageTitle': 'Arabic Language Course',
  'courseDuration': '08:30Min',

  // Exam Package Titles
  'examScienceTitle': 'Science Exam Package',
  'examMathematicsTitle': 'Mathematics Exam Package',
  'examLifeSkillsTitle': 'Life Skills Exam Package',
  'examSocialStudiesTitle': 'Social Studies Package',
  'examArabicTitle': 'Arabic Language',
  'examComputerTitle': 'Computer Exam Package',
  'examDuration': '08:30hrs',
  'examLanguage': 'English, Arabic',
  'examType': 'MCQ-based Q&A',
  'examRating': 'Rating',
  'examPrice': 'Price',
  "mathQuestion1": "What is the value of 7 × 8?",
  "mathQuestion1Option1": "54",
  "mathQuestion1Option2": "56",
  "mathQuestion1Option3": "64",
  "mathQuestion1Option4": "58",

  "mathQuestion2": "What is the square root of 144?",
  "mathQuestion2Option1": "10",
  "mathQuestion2Option2": "11",
  "mathQuestion2Option3": "12",
  "mathQuestion2Option4": "13",
  "mathQuestion3": "What is 15% of 200?",
  "mathQuestion3Option1": "20",
  "mathQuestion3Option2": "25",
  "mathQuestion3Option3": "30",
  "mathQuestion3Option4": "35",

  "mathQuestion4": "Which number is a prime number?",
  "mathQuestion4Option1": "12",
  "mathQuestion4Option2": "15",
  "mathQuestion4Option3": "17",
  "mathQuestion4Option4": "21",

  "mathQuestion5": "What is the value of 9 squared?",
  "mathQuestion5Option1": "18",
  "mathQuestion5Option2": "27",
  "mathQuestion5Option3": "72",
  "mathQuestion5Option4": "81",
  "lblSubmit": "Submit",
  "lblFinish": "Finish",

  // Course Package Titles
  'courseMathematicsTitle': 'Mathematics',
  'courseScienceTitle': 'Science',
  'courseArabicTitle': 'Arabic Language',
  'courseSocialStudiesTitle': 'Social Studies',
  'courseComputerTitle': 'Computer',
  'courseLifeSkillsTitle': 'Life Skills',
  'lblEnrollMe': 'Enroll me @valueKWD / Per Year',
  'lblEnrollSemester': 'Enroll @semester at @valueKWD / Per Year',
  'lblEnrollBothSemester': 'Enroll Both Semesters at @valueKWD / Per Year',
  'lblEnrollExamPackage': 'Enroll exam package at  @valueKWD / Per Year',

  // Learning Course Titles
  'learningCourseArabicTitle': 'Arabic Language Course',
  'learningCourseDuration': '08:30Min',

  'scheduleLiveExamReviewTitle': 'Live Exam Review',
  'scheduleLiveExamReviewSubtitle': 'Mr. Zahir Shalhoub',

  'scheduleRenewableEnergyLessonTitle': 'Renewable Energy Lesson',
  'scheduleRenewableEnergyLessonSubtitle': 'Study Plan',

  // Setting Screen
  'lblSettingsPreferences': 'Settings & Preferences',
  'lblMore': 'More',
  'lblAccount': 'Account',
  'lblLanguage': 'Language',
  'lblMySaveList': 'My Save List',
  'lblMyOrder': 'My Order',
  'lblInvoice': 'Invoice',
  'lblOrderStatus': 'Order Status',
  'lblStatistics': 'Statistics',
  'lblMyPurchases': 'My Purchases',
  'lblMyDownloads': 'My Downloads',
  'lblAboutUs': 'About Us',
  'lblFAQ': 'Frequently Asked Questions',
  'lblTermsConditions': 'Terms & Conditions',
  'lblContactUs': 'Contact Us',
  'lblDeleteAccount': 'Delete Account',
  'lblLogout': 'Logout',
  'lblAreYouSure': 'Are you sure?',
  'lblDeleteAccountInfo': 'If you’re sure you want to permanently delete\nyour account, please click Delete\naccount below',
  'lblCancel': 'Cancel',
  'lblOkay': 'Ok',
  'lblYesDelete': 'Yes, Delete',
  'lblAreYouSureLogout': 'Sure you want to Logout?',
  'lblLogoutInfo':
      'You can log out of your account anytime. Don’t worry\n- your data will be saved, and you can log back in\nwhenever you\'re ready.',
  'lblGoBack': 'Go Back',
  "lblVersion": "V ",

  // My Downloads Screen
  'lblCourseVideo': 'Course Video',
  'lblCoursePdf': 'Course PDF',

  // Notification Screen
  "notifications": "Notifications",
  "clearAll": "Clear All",
  "upcomingExamAlert": "Upcoming Exam Alert",
  "chapterDeadlineReminder": "Chapter Deadline Reminder",
  "chapterProgressReminder": "Chapter Progress Reminder",
  "pendingChapterCompletionReminder": "Pending Chapter Completion Reminder",
  "missedChapterReminder": "Missed Chapter Reminder",
  "maintainStreakReminder": "Maintain Your Streak Reminder",
  "lostStreakAlert": "Lost Streak Alert",
  "shipmentNotification": "Shipment Notifications (Term Exams)",
  "defaultMessage": "Hello! How can I help?",

  // My Save List Screen
  "mySaveList": "My Save List",
  "saveCourse": "Save Course",
  "savedChapter": "Saved Chapters",
  "savedExam": "Saved Exam",

  // Course Content
  "packageA": "Package A",
  "mathematicsDescription": "Mathematics is the language of patterns and logic, used to understand and describe the world around us...",
  "mathematics": "Mathematics",
  "factoringPolynomials": "Factoring Polynomials",
  "durationMinutes": "01:30 Min",

  // contact Us Screen
  "weLoveToHearFromYou": "We'd love to hear from you!",
  "contactUsDescription":
      "Whether you have a suggestion for improvement, a concern to discuss, or an issue that needs resolving — don't hesitate to reach out to us.",
  "callUs": "Call Us",
  "phoneNumber": "(+965) 22761129",
  "emailUs": "Email Us",
  "email": "Info@mafhoom.com",
  "connectSocialMedia": "Connect us in Social Media",
  "instagram": "Instagram",
  "instagramFollowers": "0 Followers",
  "instagramPosts": "0 Posts",
  "telegram": "Telegram",
  "telegramFollowers": "0 Followers",
  "telegramPosts": "0 Posts",
  "facebook": "Facebook",
  "facebookFollowers": "0 Followers",
  "facebookPosts": "0 Posts",
  "whatsapp": "WhatsApp",
  "whatsappAvailability": "Available Mon–Fri • 9 AM – 5 PM",
  'myCourse': "My Course",
  "noSavedCoursesYet": "No saved courses yet",
  "lblClearAll": "Clear All",
  "lblPaymentSummary": "Payment Summary",
  "lblPromoCode": "Promocode",
  "lblApplyPromoCode": 'Apply Promocode',
  "lblAllPromoCode": 'All Promocode',
  "lblApplyPromocode": "Apply Promocode",
  'lblEnterPromoCode': 'Enter Promocode Code',
  'lblApply': 'Apply',
  'lblRemove': "Remove",
  'lblOrderSummary': 'Order Summary',
  'lblSubTotal': 'Sub Total',
  'lblDiscount': 'Discount',
  'lblTotal': 'Total',
  'lblExpires': 'Expires',
  'lblPaymentFailure': 'Payment Failed',
  'lblPaymentFailureInfo': 'Payment failed your transaction has\nbeen failed.',
  'lblPayNow': 'Pay Now',
  'lblWriteReviewTitle': 'Write a review',
  'lblProductListTitle': 'Product List',
  'lblMyOrderTitle': 'My Orders',
  'lblProductDetailTitle': 'Product Detail',
  'lblCheckOutTitle': 'CheckOut',
  'lblRatingInfo': 'How would you rate the\nquality of this Product',
  'lblWriteYourReview': 'Write Your Review',
  'lblReviewHint': 'Type your review here...',
  'lblCharacterRemaining': '@value Characters Remaining',
  'lblSubmitReview': 'Submit Review',
  'lblExamAttempted': 'Exam attempted',
  'lblNoPromoCode': 'No promo code found.',
  'lblReview': "Review",
  'lblWriteReview': 'Write Review',
  'lblPleaseAddReview': 'Please provide rating',
  'lblNoReviews': 'No reviews yet.',
  "lblStarSingular": "@value star",
  "lblStarPlural": "@value stars",
  'lblGoToDashboard': 'Go to Dashboard',
  'lblWatched': 'Watched',
  'lblDownloadingPdf': 'Downloading PDF',
  'lblOpenPdf': 'Open PDF',
  'lblGoToDownloads': "Go To Downloads",
  'lbTypeHere': 'Type here...',
  'lblNoInternetInfo': 'Please check your connection and try again',
  'lblPleaseLoginToAccessLink': 'Please login to access this link.',
  'lblCheckOutThis': 'Check out this on Mafhoom: @value',
  "lblOrderDetails": "Order Details",
  "lblPurchasedOn": "Purchased On",
  "lblExpiresOn": "Expires On",
  "lblOrderId": "Order ID",
  "lblPlanType": "Plan Type",
  "lblPackageIsActive": "Package is Active",
  "lblPackageExpired": "Package has Expired",
  "lblRemainingDays": "Days Remaining",
  'lblOrderAmount': 'Order Amount',
  'lblLinkError': 'Could not open link',
  'lblEmailError': 'Could not open email client',
  'lblCallError': 'Could not initiate call',

  'lblCheckYourConnection': 'Please check your Internet connection.',
  'lblSomethingWentWrong': "Something went wrong",
  'lblAutoLogout': 'Auto logged out due to session expiration.',
  'lblSessionExpired': 'Session expired, please log in again.',
  'lbl100Message': 'Great job, @username,',
  'lbl100SubMessage': 'You done well.',
  'lbl99Message': 'Good effort!\nKeep practicing, @username',
  'lbl99SubMessage': 'You’re improving!',
  'lbl50Message': "Don’t worry!\nIt's okay, @username.",
  'lbl50SubMessage': 'This is just a start. Review the material and try again!',
  'lblExpired': 'Expired',

  'lblExamWarningMessage':
      'Leaving the app or putting it in the background during the exam will result in automatic submission, and your attempt will be considered complete.',
  'lblReadLess': 'Read Less',
};
